### PR TITLE
fix: incosistent footer

### LINKED ISSUE #208: Adjust the footer to be consistent with SFUI
┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SH-71) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://vsf.atlassian.net/rest/api/2/attachment/content/11143">Screen Shot 2022-02-02 at 12.44.38.png</a>

### PR DESCRIPTION
**Pull request by jeffpdotone**
Fixed #208 

## Description
We saw an inconsistency in the design  around the footer these changes will fix it and base it on SAP CC integration

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/theme/components/AppFooter.vue [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+        'Men fashion',
+        'Kidswear',
+        'Home'
+      ],
+      help: [
+        'Customer service',
+        'Size guide',
+        'Contact us'
+      ],
+      paymentsDelivery: ['Purchase terms', 'Guarantee'],
```
Comment (Mateuszpietrusinski) [inline packages/theme/components/AppFooter.vue:74]: all those strings should use i18n translations

File: packages/theme/components/AppFooter.vue [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+      isMobile: false,
+      desktopMin: 1024
+    };
+  }
+};
+</script>
+
+<style lang="scss">
+.footer {
+  margin-bottom: 3.75rem;
```
Comment (Mateuszpietrusinski) [inline packages/theme/components/AppFooter.vue:85]: this value should use var(--spacer-something)

File: packages/theme/components/AppFooter.vue [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+  }
+}
+.sf-footer {
+  @include for-desktop {
+    border-top: var(--spacer-xs) solid var(--c-primary);
+    padding-bottom: 0;
+    margin-top: var(--spacer-2xl);
+  }
+  &__container {
+    padding-bottom: 50px;
```
Comment (Mateuszpietrusinski) [inline packages/theme/components/AppFooter.vue:111]: same as above, we need to use the same spacing in the project

**Review by Mateuszpietrusinski — CHANGES_REQUESTED** [review]
Small adjustments needed

**Review by Mateuszpietrusinski — APPROVED** [review]
