### PR TITLE
fix(RelatedProducts): add to cart on match it with section

### LINKED ISSUE #259: Add to cart on match it with section
On the Homepage, add to cart button not working on the product card in the "Match it with" section. 

**Scenario:**

* Go to the "Match it with" section
* Go to any product card that is not out of stock
* Click on the add to cart button of the card

┆Issue is synchronized with this [Jira Błąd w programie](https://vsf.atlassian.net/browse/SH-96) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://vsf.atlassian.net/rest/api/2/attachment/content/11382">match-it-with.webm</a>

### PR DESCRIPTION
**Pull request by jeffpdotone**
Closes #259 

## Description
This will now fix disable the add to cart whenever it has no stock left

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/theme/components/RelatedProducts.vue [hunk 1]
```diff
@@ -11,19 +11,24 @@
...
             :image="productGetters.getPDPCoverImage(product)"
+            :is-added-to-cart="isInCart({ product, currentCart })"
+            :add-to-cart-disabled="getStockCount(product) <= 0"
             :link="localePath(`/p/${productGetters.getId(product)}/${productGetters.getSlug(product)}`)"
             :wishlist-icon="false"
             :image-width="295"
             :image-height="295"
             class="pdp-product-card"
+            @click:add-to-cart="
+              HandleAddTocart({ product, quantity: 1, currentCart })
```
Comment (Frodigo) [inline packages/theme/components/RelatedProducts.vue:22]: can you change the name of this function to camel case?

**Review by Frodigo — CHANGES_REQUESTED** [review]

**Review by aureate-labs-team — APPROVED** [review]
